pipeline{
    agent any
    environment{
        IMAGE_NAME = "frontend-image"
        PORT = "5147"
    }
    stages{
        stage('Fetch Code'){
            steps{
                git branch: 'Michael-stg', url: 'https://github.com/darisjerez/devops-class-frontend'
            }
        }

        stage('Dependencies'){
            steps{
                sh '''
                npm install --legacy-peer-deps
                
                '''
            }
        }

        stage('Lint'){
            steps{
                sh '''
                npm run lint
                npx prettier --write .
                npx prettier --check .
                '''
            }
        }

        stage('Test'){
            steps{
                sh '''
                npm run test
                '''
            }
        }

        stage('Build && Artifacts'){
            steps{
                sh '''
                npm run build
                '''
                archiveArtifacts artifacts: 'dist/**', fingerprint: true
            }
        }

        stage('Docker Build && Run Locally'){
            steps{
                sh """
                docker build -t ${IMAGE_NAME}:${env.BUILD_NUMBER} .
                docker run -d -p ${PORT}:5147 ${IMAGE_NAME}:${env.BUILD_NUMBER}
                """
            }
        }
    } 

    post {
        always {
            echo 'Finished pipeline'
        }
        success {
            echo 'Has been success'
        }
        failure{
            echo 'Failured pipeline'
        }
    }   
}
